# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            WSDS Conference
tagline:          '2020 WSDS Conference'
description:      'Probabilistic Methods in Time Series Analysis: A Case Study presented by Sarah Cameron, Valerie Schnapp, and Lindsay Truong'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
